apps/course/urls.py
#!/usr/bin/python3
# _*_ coding: utf-8 _*_
from . import views
from django.urls import path


app_name = 'course'


urlpatterns = [
    path('', views.course_index, name='course-index'),
    path('<int:course_id>/', views.course_detail, name='course-detail'),
    path('order/<int:course_id>/', views.course_order, name='course-order'),
    path("token/", views.course_token, name='course-token'),
]

xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.index, name='index'),
    path('search/', include('haystack.urls')),
    path('news/', include('apps.news.urls')),
    path('course/', include('apps.course.urls')),
    path('pay/', include('apps.payinfo.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.xfzauth.urls')),
    path("ueditor/", include('apps.ueditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

apps/course/models.py
#!/usr/bin/python3
# _*_ coding: utf-8 _*_
from django.db import models
from apps.models import ModelMixin


class CourseCategory(models.Model):
    name = models.CharField(max_length=200)


class Teacher(models.Model):
    nickname = models.CharField(max_length=20)
    avatar = models.URLField()
    position = models.CharField(max_length=200)
    profile = models.TextField()


class Course(ModelMixin):
    name = models.CharField(max_length=200)
    category = models.ForeignKey('CourseCategory', on_delete=models.DO_NOTHING)
    teacher = models.ForeignKey("Teacher", on_delete=models.DO_NOTHING)
    video_link = models.URLField()
    cover_link = models.URLField()
    price = models.FloatField()
    duration = models.IntegerField()
    desc = models.TextField(default="暂无描述信息")
    pub_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"(<Course>: {self.name}, {self.id})"

apps/course/views.py
#!/usr/bin/python3
# _*_ coding: utf-8 _*_
import hashlib
import hmac
import os
import time

from django.conf import settings
from django.shortcuts import render

from .models import Course
from utils import restfuls


def course_index(request):
    courses = Course.objects.select_related('teacher').all()
    context = {
        'courses': courses
    }
    return render(request, 'course/course_index.html', context)


def course_detail(request, course_id):
    course = Course.objects.prefetch_related('teacher').get(pk=course_id)
    context = {
        'course': course
    }
    return render(request, 'course/course_detail.html', context)


def course_token(request):
    """百度云播放视频"""
    file = request.GET.get('video')

    expiration_time = int(time.time()) + 2 * 60 * 60
    USER_ID = settings.BAIDU_CLOUD_USER_ID
    USER_KEY = settings.BAIDU_CLOUD_USER_KEY

    extension = os.path.splitext(file)[1]  # 获取扩展名
    media_id = file.split('/')[-1].replace(extension, '')

    key = USER_KEY.encode('utf-8')
    message = f"/{media_id}/{expiration_time}".encode('utf-8')
    signature = hmac.new(key, message, digestmod=hashlib.sha256).hexdigest()
    token = f"{signature}_{USER_ID}_{expiration_time}"
    return restfuls.success(data={"token": token})


def course_order(request, course_id):
    course = Course.objects.get(pk=course_id)
    context = {
        'course': course
    }
    return render(request, 'course/course_order.html', context)

front/templates/course/course_detail.html
{% extends 'base/front_base.html' %}

{% block title %}
   {{ course.name }}
{% endblock %}

{% block head %}
   <link rel="stylesheet" href="{% static 'css/course/course_detail.min.css' %}">

   <script src="{% static 'js/videojs/video.min.js' %}"></script>
   <script src="{% static 'js/videojs/videojs-contrib-hls.min.js' %}"></script>
   <script src="{% static 'js/videojs/videojs-contrib-quality-levels.min.js' %}"></script>
   <script type="text/javascript" src="{% static 'js/videojs/cyberplayer.js' %}"></script>

   <script src="{% static 'js/course_detail.min.js' %}"></script>
{% endblock %}

{% block main %}
   <div class="main">
      {% include 'course/course_nav.html' %}
      <div class="wrapper">
         <div class="course-wrapper">
            <div class="course-info">
               <p class="course-title">{{ course.name }}</p>
               <div class="price-group">
                  <div class="share-group">
                     <span class="title">分享至：</span>
                  </div>
                  <div class="buy-group">
                     {% if course.price > 0 %}
                        <span class="price pay">￥{{ course.price }}</span>
                        <a href="{% url 'course:course-order' course.pk %}" class="buy-btn">立即购买</a>
                     {% else %}
                        <span class="price free">免费</span>
                     {% endif %}
                  </div>
               </div>
            </div>
            <div class="video-group">
               <span id="video-info" hidden data-video="{{ course.video_link }}" data-cover="{{ course.cover_link }}"></span>
               <div id="playercontainer"></div>
            </div>
         </div>
         <div class="bottom-wrapper">
            <div class="course-detail-wrapper">
               <div class="item-group">
                  <p class="item-title">课程讲师</p>
                  <div class="teacher-group">
                     <div class="avatar-group">
                        <img src="https://adminlte.io/themes/AdminLTE/dist/img/user2-160x160.jpg" alt="" class="avatar">
                     </div>
                     <div class="teacher-info">
                        <p class="teacher-name">{{ course.teacher.nickname }}</p>
                        <p class="teacher-desc">{{ course.teacher.position }}</p>
                     </div>
                  </div>
                  <p class="item-content">
                     {{ course.teacher.profile|safe }}
                  </p>
               </div>
               <div class="item-group">
                  <p class="item-title">课程简介</p>
                  <p class="item-content">
                     {{ course.desc|safe }}
                  </p>
               </div>
               <div class="item-group">
                  <p class="item-title">课程大纲</p>
                  <p class="item-content">
                     小饭桌在线课堂是小饭桌旗下的线上视频课程产品，汇聚顶级创业大咖导师、行业资深专家，致力于用系统、垂直的知识体系让创业者认知升级、技能进阶。小饭桌在线课堂用知识陪伴创业者从平凡到卓越！
                  </p>
               </div>
               <div class="item-group">
                  <p class="item-title">适宜人群</p>
                  <p class="item-content">想学习如何做投资的！
                  </p>
               </div>
               <div class="item-group">
                  <p class="item-title">帮助中心</p>
                  <p class="item-content">
                     1. 购买后的课程在线可反复观看学习，视频有效期以具体课程信息为准。 <br>
                     2. 课程暂不支持下载观看，均为在线观看视频。 <br>
                     3. 课程一经购买，不可转让、不可退款；仅限购买账号观看。 <br>
                     4. 如有问题请咨询客服饭桌君： 电话：18618172287 微信：fanzhuojun888 <br>
                  </p>
               </div>
               <div class="item-group">
                  <p class="item-title">关于小饭桌在线课堂</p>
                  <p class="item-content">
                     小饭桌在线课堂是小饭桌旗下的线上视频课程产品，汇聚顶级创业大咖导师、行业资深专家，致力于用系统、垂直的知识体系让创业者认知升级、技能进阶。小饭桌在线课堂用知识陪伴创业者从平凡到卓越！
                  </p>
               </div>
            </div>
            <div class="recommand-wrapper">
               <p class="recommand-title">推荐课程</p>
               <ul class="course-list">
                  <li>
                     <a href="#">
                        <div class="course-info-group">
                           <p class="course-title">教你制作抓住投资人眼球的商业计划书</p>
                           <p class="teacher">知了课堂CEO</p>
                        </div>
                        <div class="thumbnail-group">
                           <img src="https://static-image.xfz.cn/1526455098_289.png-course.list.small" alt=""
                                class="thumbnail">
                        </div>
                     </a>
                  </li>
                  <li>
                     <a href="#">
                        <div class="course-info-group">
                           <p class="course-title">教你制作抓住投资人眼球的商业计划书</p>
                           <p class="teacher">知了课堂CEO</p>
                        </div>
                        <div class="thumbnail-group">
                           <img src="https://static-image.xfz.cn/1526455098_289.png-course.list.small" alt=""
                                class="thumbnail">
                        </div>
                     </a>
                  </li>
               </ul>
            </div>
         </div>
      </div>
   </div>
{% endblock %}

front/templates/course/course_index.html
{% extends 'base/front_base.html' %}


{% block title %}
   创业课堂
{% endblock %}


{% block head %}
   <link rel="stylesheet" href="{% static 'css/course/course_index.min.css' %}">
{% endblock %}


{% block main %}
   <div class="main">
      {% include 'course/course_nav.html' %}
      <div class="wrapper">
         <ul class="course-list">
            {% for course in courses %}
               <li>
                  <a href="{% url 'course:course-detail' course.pk %}">
                     <div class="thumbnail-group">
                        <img src="{{ course.cover_link }}" alt="" class="thumbnail">
                     </div>
                     <div class="course-info">
                        <p class="title">{{ course.name }}</p>
                        <p class="author">{{ course.teacher.nickname }}</p>
                        <p class="price-group">
                           {% if course.price > 0 %}
                              <span class="pay">￥{{ course.price}}</span>
                           {% else %}
                              <span class="free">免费</span>
                           {% endif %}
                        </p>
                     </div>
                  </a>
               </li>
            {% endfor %}
         <li style="background-color: transparent"></li>
         </ul>
      </div>
   </div>
{% endblock %}

front/templates/course/course_nav.html
<div class="course-nav">
            <div class="nav-container">
                <h3 class="title">在线课堂</h3>
                <ul class="nav-list">
                    <li class="active"><a href="#">最新课堂</a></li>
                    <li><a href="#">投资人说</a></li>
                    <li><a href="#">明星案例</a></li>
                    <li><a href="#">创业知识</a></li>
                </ul>
            </div>
        </div>

front/templates/course/course_order.html
{% extends 'base/front_base.html' %}

{% block title %}
   确认订单
{% endblock %}

{% block head %}
   <link rel="stylesheet" href="{% static 'css/common/header.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/common/footer.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/common/body.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/course/course_order.min.css' %}">

   <script src="{% static 'js/course_order.min.js' %}"></script>
{% endblock %}

{% block main %}
   <div class="main">
      <div class="wrapper">
         <table class="table">
            <thead>
            <tr>
               <th></th>
               <th>商品名称</th>
               <th>单价(元)</th>
               <th>小计（元）</th>
            </tr>
            </thead>
            <tbody>
            <tr>
               <td align="left">
                  <a href="{% url 'course:course-detail' course.pk %}">
                     <img class="thumbnail" src="{{ course.cover_link }}" alt="">
                  </a>

               </td>
               <td><span class="title">{{ course.name }}</span></td>
               <td>{{ course.price }}</td>
               <td>{{ course.price }}</td>
            </tr>
            </tbody>
         </table>
         <form action="https://pay.bbbapi.com/" method="post" id="pay-form">
            <input type="hidden" name="uid" value="49dc532695baa99e16e01bc0">
            <input type="hidden" name="price" value="{{ course.price }}">
            <input type="hidden" name="notify_url" value="{{ notify_url }}">
            <input type="hidden" name="return_url" value="{{ return_url }}">
            <input type="hidden" name="orderid" value="{{ order.pk }}">
            <input type="hidden" name="orderuid" value="{{ request.user.pk }}">
            <input type="hidden" name="goodsname" value="{{ course.name }}">
            <input type="hidden" name="key" value="">
            <div class="pay-way">
               <label for="istype-wx">
                  <input id="istype-wx" type="radio" name="istype" value="2">
                  <span class="wx-btn">
                        <img src="http://nos.netease.com/test-edu-image/1BD9F69D6760CE1508D2269864AA54F8.png" alt="">
                    </span>
               </label>
               <label for="istype-zfb">
                  <input id="istype-zfb" type="radio" name="istype" value="1" checked>
                  <span class="zfb-btn"></span>
               </label>
               <div style="clear: both;"></div>
            </div>
            <div class="submit-group">
               <input type="submit" value="去支付" id="submit-btn" class="submit-btn">
            </div>
         </form>
      </div>
   </div>
{% endblock %}