apps/cms/urls.py
#!/usr/bin/python3
# _*_ coding: utf-8 _*_

from . import views, staff_view
from django.urls import path

app_name = 'cms'

urlpatterns = [
    path('', views.index, name='index'),
    # 新闻 映射
    path('news/publish/', views.PublishNewsView.as_view(), name='publish-news'),
    path('news/category/', views.news_category, name='news-category'),
    path("news/category/add/", views.add_news_category, name='add-news-category'),
    path("news/category/edit/", views.edit_news_category, name='edit-news-category'),
    path("news/category/delete/", views.delete_category_category, name='delete-news-category'),
    path("news/list/", views.NewsListView.as_view(), name='news-list'),
    path("news/edit/", views.edit_news, name='news-edit'),
    path("news/remove/", views.remove_news, name='news-remove'),

    path('qntoken/', views.qntoken, name='qntoken'),  # 上传文件到七牛云
    path("upload/", views.upload_file, name='upload'),  # 上传文件到本地
]

# 轮播图管理
urlpatterns += [
    path("banner/", views.banner, name='banner'),
    path('banner/add/', views.add_banner, name="banner-add"),
    path('banner/edit/', views.edit_banner, name="banner-edit"),
    path('banner/load/', views.load_banner, name='banner-load'),
    path("banner/remove/", views.remove_banner, name='banner-remove'),
]

# 课程管理
urlpatterns += [
    path('course/publish/', views.PublishCourseView.as_view(), name='course-publish'),
]

# 员工管理
urlpatterns += [
    path("staff/", staff_view.staff_operate, name='staff-operate'),
    path('staff/add/', staff_view.AddStaffView.as_view(), name="staff-add"),
    path("staff/remove/", staff_view.remove_staff, name='staff-remove'),
    path("staff/update/", staff_view.UpdateStaffView.as_view(), name='staff-update'),
]

apps/xfzauth/urls.py
#!/usr/bin/python3
# _*_ coding: utf-8 _*_
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_captcha, name='sms_captcha'),
]


# 测试数据
from . import test
urlpatterns += [
    path('test/', test.test_index, name='test-index'),
]

xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.index, name='index'),
    path('search/', include('haystack.urls')),
    path('news/', include('apps.news.urls')),
    path('course/', include('apps.course.urls')),
    path('pay/', include('apps.payinfo.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.xfzauth.urls')),
    path("ueditor/", include('apps.ueditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

apps/cms/models.py
from django.db import models


class Banner(models.Model):
    priority = models.IntegerField(default=0)
    image_url = models.URLField()
    link_to = models.URLField()
    pub_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-priority', '-pub_time']

apps/course/models.py
#!/usr/bin/python3
# _*_ coding: utf-8 _*_
from django.db import models
from apps.models import ModelMixin


class CourseCategory(models.Model):
    name = models.CharField(max_length=200)


class Teacher(models.Model):
    nickname = models.CharField(max_length=20)
    avatar = models.URLField()
    position = models.CharField(max_length=200)
    profile = models.TextField()


class Course(ModelMixin):
    name = models.CharField(max_length=200)
    category = models.ForeignKey('CourseCategory', on_delete=models.DO_NOTHING)
    teacher = models.ForeignKey("Teacher", on_delete=models.DO_NOTHING)
    video_link = models.URLField()
    cover_link = models.URLField()
    price = models.FloatField()
    duration = models.IntegerField()
    desc = models.TextField(default="暂无描述信息")
    pub_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"(<Course>: {self.name}, {self.id})"

apps/news/models.py
from django.db import models


class NewsCategory(models.Model):
    name = models.CharField(max_length=100)


class News(models.Model):
    title = models.CharField(max_length=255)
    desc = models.CharField(max_length=255)
    thumbnail = models.URLField()
    content = models.TextField()
    # 多对一关系
    category = models.ForeignKey('NewsCategory', on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey('xfzauth.User', on_delete=models.DO_NOTHING, null=True)
    pub_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-pub_time']


class Comment(models.Model):
    # 新闻评论
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    news = models.ForeignKey("News", related_name='comments',
                             on_delete=models.CASCADE)
    author = models.ForeignKey("xfzauth.User", related_name='comments',
                               on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.news_id}: {self.content}"

    class Meta:
        ordering = ('-pub_time',)

apps/cms/views.py
import os
from datetime import datetime
from urllib import parse

import qiniu
from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import permission_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.utils.decorators import method_decorator
from django.utils.timezone import make_aware
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST, require_GET
from django.views.generic.base import View

from apps.cms.forms import PublishNewsForm
from apps.course.models import Course, CourseCategory, Teacher
from apps.news.models import NewsCategory, News
from utils import restfuls
from .forms import (
    EditNewsCategoryForm,
    AddBannerForm,
    EditBannerForm,
    PublishCourseForm
)
from .models import Banner
from .serializers import BannerSerializer


@staff_member_required(login_url=reverse_lazy("cms:index"))
def index(request):
    return render(request, 'cms/index.html')


class PublishNewsView(View):
    """发布/编辑新闻"""

    def get(self, request):
        categories = NewsCategory.objects.all()
        context = {
            "categories": categories
        }
        return render(request, 'cms/publish_news.html', context=context)

    def post(self, request):
        form = PublishNewsForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            cid = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=cid)

            news_id = form.cleaned_data.get('news_id') or None
            News.objects.update_or_create(id=news_id, defaults={
                "title": title,
                "desc": desc,
                "thumbnail": thumbnail,
                "content": content,
                "category": category,
                "author": request.user
            })
            return restfuls.success()
        return restfuls.bad_request(msg=form.get_errors())


@permission_required(perm='news.change_news', login_url=reverse_lazy("cms:index"))
@require_GET
def news_category(request):
    categories = NewsCategory.objects.all()
    context = {
        "categories": categories,
    }
    return render(request, 'cms/news_category.html', context=context)


@permission_required(perm='news.change_news', login_url=reverse_lazy("cms:index"))
@require_POST
def add_news_category(request):
    name = request.POST.get('name')
    exists = NewsCategory.objects.filter(name=name).exists()
    if not exists:
        NewsCategory.objects.create(name=name)
        return restfuls.success(msg="添加成功")
    return restfuls.bad_request(msg="该分类已经存在")


@permission_required(perm='news.change_news', login_url=reverse_lazy("cms:index"))
@require_POST
def edit_news_category(request):
    form = EditNewsCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            NewsCategory.objects.filter(pk=pk).update(name=name)
            return restfuls.success()
        except ValueError:
            return restfuls.bad_request(msg="该分类已不存在")
    return restfuls.bad_request(form.get_errors())


@permission_required(perm='news.change_news', login_url=reverse_lazy("cms:index"))
@require_POST
def delete_category_category(request):
    pk = request.POST.get("pk")
    if pk:
        NewsCategory.objects.filter(pk=pk).delete()
        return restfuls.success()
    return restfuls.bad_request(msg="当前分类已不存在")


@method_decorator(permission_required(perm='news.change_news', login_url=reverse_lazy("cms:index")), name='dispatch')
class NewsListView(View):
    # 新闻列表
    def get(self, request):
        p = request.GET.get("p", 1)  # 获取当前是第几页
        start_time = request.GET.get('start', '')
        end_time = request.GET.get('end', '')
        title = request.GET.get("title", '')
        category_id = int(request.GET.get("category", 0))

        categories = NewsCategory.objects.all()
        newses = News.objects.select_related('author', 'category')

        # 按照新闻时间进行过滤
        if start_time or end_time:
            start_time = start_time[:10]
            end_time = end_time[:10]
            if start_time:
                try:
                    start_time = datetime.strptime(start_time, '%Y/%m/%d')
                except ValueError:
                    start_time = datetime.strptime(start_time, '%Y-%m-%d')
            else:
                start_time = datetime(year=2019, month=6, day=1)

            if end_time:
                try:
                    end_time = datetime.strptime(end_time, '%Y/%m/%d')
                except ValueError:
                    end_time = datetime.strptime(end_time, '%Y-%m-%d')
            else:
                end_time = datetime.today()
            newses = newses.filter(pub_time__range=(make_aware(start_time), make_aware(end_time)))

        # 按照标题进行过滤
        if title:
            newses = newses.filter(title__icontains=title)

        # 按照分类进行过滤
        if category_id != 0:
            newses = newses.filter(category=category_id)

        paginator = Paginator(newses, 6)  # 每页显示多少条数据
        page_obj = paginator.get_page(p)
        rt_pages = self.get_paginator_page(paginator, page_obj)
        context = {
            'newses': page_obj.object_list,
            "categories": categories,
            'url_query': "&" + parse.urlencode({
                'start': start_time,
                'end': end_time,
                'title': title,
                'category': category_id or 0,
            }),
            'start': start_time,
            'end': end_time,
            'title': title,
            'category_id': category_id or 0,
        }
        context.update(**rt_pages)
        return render(request, 'cms/news_list.html', context=context)

    def get_paginator_page(self, paginator, page_obj, around_num=2):
        current_page = page_obj.number
        num_pages = paginator.num_pages

        left_has_more = False
        right_has_more = False

        # current_page=around_num+2时, (1, current_page)
        if current_page <= around_num + 2:
            left_pages = range(1, current_page)
        else:
            left_has_more = True
            left_pages = range(current_page - around_num, current_page)  # 左列表页

        # current_page=num_page-around_num-1时就要(current_page, num_pages)
        if current_page >= num_pages - around_num - 1:
            right_pages = range(current_page + 1, num_pages + 1)
        else:
            right_has_more = True
            right_pages = range(current_page + 1, current_page + around_num + 1)  # 右列表页

        rt_pages = {
            'current_page': current_page,
            "left_pages": left_pages,
            'right_pages': right_pages,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            "num_pages": num_pages,
            "page_obj": page_obj,
            'paginator': paginator,
        }
        return rt_pages


@permission_required(perm='news.change_news', login_url=reverse_lazy("cms:index"))
def edit_news(request):
    news_id = request.GET.get("news")
    try:
        news = News.objects.get(pk=news_id)
    except News.DoesNotExist:
        return restfuls.bad_request(msg="该新闻已不存在")
    categories = NewsCategory.objects.all()
    context = {
        "news": news,
        'categories': categories,
    }
    return render(request, 'cms/publish_news.html', context=context)


@permission_required(perm='news.change_news', login_url=reverse_lazy("cms:index"))
@require_POST
def remove_news(request):
    news_id = request.POST.get('news')
    try:
        News.objects.get(pk=news_id).delete()
        return restfuls.success()
    except News.DoesNotExist:
        return restfuls.bad_request(msg="该新闻已不存在")


# 轮播图管理
@permission_required(perm='news.change_news', login_url=reverse_lazy("cms:index"))
def banner(request):
    # 管理轮播图
    return render(request, 'cms/banner.html')


@permission_required(perm='news.change_news', login_url=reverse_lazy("cms:index"))
def load_banner(request):
    # ajax 加载轮播图
    banners = Banner.objects.all()
    serializer = BannerSerializer(banners, many=True)
    return restfuls.success(data=serializer.data)


@permission_required(perm='news.change_news', login_url=reverse_lazy("cms:index"))
@require_POST
def add_banner(request):
    # 添加轮播图
    form = AddBannerForm(request.POST)
    if form.is_valid():
        priority = form.cleaned_data.get('priority')
        image_url = form.cleaned_data.get('image_url')
        link_to = form.cleaned_data.get('link_to')
        banner = Banner.objects.create(priority=priority, image_url=image_url, link_to=link_to)
        return restfuls.success(data={"banner_id": banner.pk})
    return restfuls.bad_request(form.get_errors())


@permission_required(perm='news.change_news', login_url=reverse_lazy("cms:index"))
@require_POST
def edit_banner(request):
    # 修改轮播图
    form = EditBannerForm(request.POST)
    if form.is_valid():
        banner_id = form.cleaned_data.get('pk')
        image_url = form.cleaned_data.get('image_url')
        link_to = form.cleaned_data.get('link_to')
        priority = form.cleaned_data.get('priority')
        try:
            Banner.objects.filter(pk=banner_id).update(image_url=image_url,
                                                       link_to=link_to,
                                                       priority=priority)
            return restfuls.success()
        except Banner.DoesNotExist:
            return restfuls.bad_request(msg="当前轮播图已不存在")
    return restfuls.bad_request(msg=form.get_errors())

front/templates/cms/add_staff.html
{% extends 'cms/base.html' %}
{% load news_filter %}


{% block title %}
   {% if staff %}
      编辑员工
   {% else %}
      添加员工
   {% endif %}
{% endblock %}


{% block content_header %}
   {% if staff %}
      编辑员工
   {% else %}
      添加员工
   {% endif %}
{% endblock %}


{% block content %}
   <div class="row">
      <div class="col-md-6 col-md-offset-3">
         <div class="box box-primary">
            <div class="box-body">
               <form action="" method="post">
                  {% csrf_token %}
                  <div class="form-group">
                     <label for="staff-tel">手机号码:</label>
                     {% if staff %}
                        <input type="text" id="staff-tel" name="telephone" value="{{ staff.telephone }}" class="form-control" placeholder="员工手机号码" readonly>
                     {% else %}
                        <input type="text" id="staff-tel" name="telephone" class="form-control" placeholder="员工手机号码">
                     {% endif %}
                  </div>
                  <div class="checkbox">
                     {% for group in groups %}
                        {% if group in staff_groups %}
                           <label style="margin-right: 14px">
                              <input name="group" type="checkbox" value="{{ group.pk }}" checked>{{ group.name }}
                           </label>
                        {% else %}
                           <label style="margin-right: 14px">
                              <input name="group" type="checkbox" value="{{ group.pk }}">{{ group.name }}
                           </label>
                        {% endif %}
                     {% endfor %}
                  </div>
                  <div class="form-group">
                     <button class="btn btn-primary pull-right" id="add-btn">确认添加</button>
                  </div>
               </form>
            </div>
            <div class="box box-footer">
               {% if messages %}
                  <ul>
                     {% for message in messages %}
                        <li style="color: #f00;">{{ message|dict_or_str }}</li>
                     {% endfor %}
                  </ul>
               {% endif %}
            </div>
         </div>
      </div>
   </div>
{% endblock %}

{% block bottom-head %}
   <script src="{% static 'js/cms/staff_operate.min.js' %}"></script>
{% endblock %}

front/templates/cms/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <title>{% block title %}{% endblock %} | 小饭桌管理系统</title>
   <!-- Tell the browser to be responsive to screen width -->
   <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
   <!-- Bootstrap 3.3.7 -->
   <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
   <!-- Font Awesome -->
   <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
   <!-- Theme style -->
   <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
   <!-- AdminLTE Skins. Choose a skin from the css/skins
        folder instead of downloading all of them to reduce the load. -->
   <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
   <!-- bootstrap wysihtml5 - text editor -->
   <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
   <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
   {% include 'base/csrf_include.html' %}
   {% block head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

   {#   头部导航栏#}
   <header class="main-header">
      <!-- Logo -->
      <a href="{% url 'cms:index' %}" class="logo">
         <!-- mini logo for sidebar mini 50x50 pixels -->
         <span class="logo-mini"><b>C</b>ms</span>
         <!-- logo for regular state and mobile devices -->
         <span class="logo-lg"><b>BACK</b>Admin</span>
      </a>
      <!-- Header Navbar: style can be found in header.less -->
      <nav class="navbar navbar-static-top">
         <!-- Sidebar toggle button-->
         <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
         </a>

         <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
               <!-- User Account: style can be found in dropdown.less -->
               <li class="dropdown user user-menu">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                     <img src="https://cdn.pixabay.com/photo/2016/11/18/23/38/child-1837375_960_720.png"
                          class="user-image" alt="User Image">
                     <span class="hidden-xs">{{ user.username }}</span>
                  </a>
                  <ul class="dropdown-menu">
                     <!-- User image -->
                     <li class="user-header">
                        <img src="https://cdn.pixabay.com/photo/2016/11/18/23/38/child-1837375_960_720.png"
                             class="img-circle" alt="User Image">

                        <p>
                           职位简单介绍
                           <small>2016-10-25 加入</small>
                        </p>
                     </li>
                     <!-- Menu Footer-->
                     <li class="user-footer">
                        <div class="pull-left">
                           <a href="#" class="btn btn-default btn-flat">个人中心</a>
                        </div>
                        <div class="pull-right">
                           <a href="{% url 'account:logout' %}" class="btn btn-default btn-flat">注销</a>
                        </div>
                     </li>
                  </ul>
               </li>
            </ul>
         </div>
      </nav>
   </header>

   {#   左侧边栏#}
   <aside class="main-sidebar">
      <!-- sidebar: style can be found in sidebar.less -->
      <section class="sidebar">
         <!-- 搜索框 -->
         <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
               <input type="text" name="q" class="form-control" placeholder="查询...">
               <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
         </form>
         <!-- /.search form -->
         <!-- sidebar menu: : style can be found in sidebar.less -->
         <ul class="sidebar-menu" data-widget="tree">
            <li>
               <a href="{% url 'cms:index' %}">
                  <i class="fa fa-home"></i>
                  <span>首页</span>
               </a>
            </li>
            {% if perms.news.change_news %}
               <li class="header">新闻管理</li>
               <li>
                  <a href="{% url 'cms:news-list' %}">
                     <i class="fa fa-list "></i>
                     <span>新闻列表</span>
                  </a>
               </li>
               <li>
                  <a href="{% url 'cms:publish-news' %}">
                     <i class="fa fa-edit "></i>
                     <span>发布新闻</span>
                  </a>
               </li>
               <li>
                  <a href="{% url 'cms:news-category' %}">
                     <i class="fa fa-tags "></i>
                     <span>新闻分类</span>
                  </a>
               </li>
               <li class="header">轮播图管理</li>
               <li>
                  <a href="{% url 'cms:banner' %}">
                     <i class="fa fa-object-ungroup "></i>
                     <span>轮播图</span>
                  </a>
               </li>
            {% endif %}
            {% if perms.course.delete_course %}
               <li class="header">课程管理</li>
               <li>
                  <a href="{% url 'cms:course-publish' %}">
                     <i class="fa fa-video-camera"></i>
                     <span>发布课程</span>
                  </a>
               </li>
            {% endif %}
            {% if user.is_superuser %}
               <li class="header">员工管理</li>
               <li>
                  <a href="{% url 'cms:staff-operate' %}">
                     <i class="fa fa-group"></i>
                     <span>员工管理</span>
                  </a>
               </li>
            {% endif %}
         </ul>
      </section>
   </aside>

   <div class="content-wrapper">
      <!-- 内容头部 -->
      <section class="content-header">
         <h3 class="text-center">{% block content_header %}{% endblock %}</h3>
      </section>

      <!-- 主体内容 -->
      <section class="content">
         {% block content %}{% endblock %}
      </section>
   </div>

   <footer class="main-footer">
      小饭桌后台管理系统
   </footer>
</div>
{% block bottom-head %}{% endblock %}
<script src="{% static 'js/message.min.js' %}"></script>
<!-- sweetalert 模态框 -->
<script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
<script src="{% static 'js/swalert.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'adminlte/dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'adminlte/dist/js/demo.js' %}"></script>
</body>
</html>

front/templates/cms/index.html
{% extends 'cms/base.html' %}


{% block title %}
   首页
{% endblock %}


{% block head %}

{% endblock %}


{% block content_header %}
<div class="title" style="margin: 0 auto;">管理版规</div>
{% endblock %}


{% block content %}
相关版规
{% endblock %}

front/templates/cms/news_category.html
{% extends 'cms/base.html' %}


{% block title %}
   新闻分类
{% endblock %}


{% block head %}
   <script src="{% static 'js/cms/news_category.min.js' %}"></script>
{% endblock %}


{% block content_header %}
   新闻分类
{% endblock %}

{% block content %}
   <div class="row">
      <div class="col-md-8 col-md-offset-2">
         <div class="box box-primary">
            <div class="box-header">
               <button id="add-btn" class="btn btn-primary pull-right">添加分类</button>
            </div>
            <div class="box-body">
               <table class="table table-bordered" id="category-table">
                  <thead>
                  <tr>
                     <th>分类</th>
                     <th>新闻数量</th>
                     <th>操作</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for category in categories %}
                     <tr data-pk="{{ category.pk }}" data-name="{{ category.name }}">
                        <td>{{ category.name }}</td>
                        <td>{{ category.news_set.count|default:0 }}</td>
                        <td>
                           <button class="btn-xs btn-warning edit-btn">编辑</button>
                           <button class="btn-xs btn-danger delete-btn">删除</button>
                        </td>
                     </tr>
                  {% endfor %}

                  </tbody>
               </table>
            </div>
         </div>
      </div>
   </div>
{% endblock %}

front/templates/cms/staff_operate.html
{% extends 'cms/base.html' %}

{% block title %}
   员工管理
{% endblock %}


{% block head %}

{% endblock %}

{% block content_header %}
   员工管理
{% endblock %}


{% block content %}
   <div class="row">
      <div class="col-md-8 col-md-offset-2">
         <div class="box box-primary">
            <div class="box-header">
               <a href="{% url 'cms:staff-add' %}" class="btn btn-primary pull-right">添加员工</a>
            </div>
            <div class="box-body">
               <table class="table table-bordered">
                  <thead>
                  <tr>
                     <th>昵称</th>
                     <th>手机号码</th>
                     <th>所属组</th>
                     <th>管理</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for staff in staffs %}
                     <tr>
                        <td>{{ staff.username }}</td>
                        <td>{{ staff.telephone }}</td>
                        <td>
                           {% if staff.is_superuser %}
                              超级管理员
                           {% else %}
                              {% for group in staff.groups.all %}
                                 {% if forloop.last %}
                                    {{ group.name }}
                                 {% else %}
                                    {{ group.name }}/
                                 {% endif %}
                              {% endfor %}
                           {% endif %}
                        </td>
                        <td>
                           {% if staff == user %}
                              <button class="btn btn-warning btn-xs" disabled>不可操作</button>
                           {% else %}
                              <a href="{% url 'cms:staff-update' %}?staff={{ staff.pk }}" class="btn btn-info btn-xs edit-staff" data-id="{{ staff.pk }}">修改组</a>
                              <button class="btn btn-danger btn-xs remove-staff" data-id="{{ staff.pk }}">删除</button>
                           {% endif %}
                        </td>
                     </tr>
                  {% endfor %}

                  </tbody>
               </table>
            </div>
            <div class="box-footer"></div>
         </div>
      </div>
   </div>
{% endblock %}


{% block bottom-head %}
<script src="{% static 'js/cms/staff_operate.min.js' %}"></script>
{% endblock %}