apps/cms/urls.py
#!/usr/bin/python3
# _*_ coding: utf-8 _*_

from . import views, staff_view
from django.urls import path

app_name = 'cms'

urlpatterns = [
    path('', views.index, name='index'),
    # 新闻 映射
    path('news/publish/', views.PublishNewsView.as_view(), name='publish-news'),
    path('news/category/', views.news_category, name='news-category'),
    path("news/category/add/", views.add_news_category, name='add-news-category'),
    path("news/category/edit/", views.edit_news_category, name='edit-news-category'),
    path("news/category/delete/", views.delete_category_category, name='delete-news-category'),
    path("news/list/", views.NewsListView.as_view(), name='news-list'),
    path("news/edit/", views.edit_news, name='news-edit'),
    path("news/remove/", views.remove_news, name='news-remove'),

    path('qntoken/', views.qntoken, name='qntoken'),  # 上传文件到七牛云
    path("upload/", views.upload_file, name='upload'),  # 上传文件到本地
]

# 轮播图管理
urlpatterns += [
    path("banner/", views.banner, name='banner'),
    path('banner/add/', views.add_banner, name="banner-add"),
    path('banner/edit/', views.edit_banner, name="banner-edit"),
    path('banner/load/', views.load_banner, name='banner-load'),
    path("banner/remove/", views.remove_banner, name='banner-remove'),
]

# 课程管理
urlpatterns += [
    path('course/publish/', views.PublishCourseView.as_view(), name='course-publish'),
]

# 员工管理
urlpatterns += [
    path("staff/", staff_view.staff_operate, name='staff-operate'),
    path('staff/add/', staff_view.AddStaffView.as_view(), name="staff-add"),
    path("staff/remove/", staff_view.remove_staff, name='staff-remove'),
    path("staff/update/", staff_view.UpdateStaffView.as_view(), name='staff-update'),
]

apps/course/urls.py
#!/usr/bin/python3
# _*_ coding: utf-8 _*_
from . import views
from django.urls import path


app_name = 'course'


urlpatterns = [
    path('', views.course_index, name='course-index'),
    path('<int:course_id>/', views.course_detail, name='course-detail'),
    path('order/<int:course_id>/', views.course_order, name='course-order'),
    path("token/", views.course_token, name='course-token'),
]

apps/payinfo/urls.py
#!/usr/bin/python3
# _*_ coding: utf-8 _*_

from . import views
from django.urls import path

app_name = 'payinfo'

urlpatterns = [
    path('', views.index, name='index'),
]

apps/xfzauth/urls.py
#!/usr/bin/python3
# _*_ coding: utf-8 _*_
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_captcha, name='sms_captcha'),
]


# 测试数据
from . import test
urlpatterns += [
    path('test/', test.test_index, name='test-index'),
]

xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.index, name='index'),
    path('search/', include('haystack.urls')),
    path('news/', include('apps.news.urls')),
    path('course/', include('apps.course.urls')),
    path('pay/', include('apps.payinfo.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.xfzauth.urls')),
    path("ueditor/", include('apps.ueditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

front/templates/base/csrf_include.html
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/ajaxSetup.min.js' %}"></script>
<script>
    $.ajaxSetup({
        data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
    });
</script>

front/templates/base/front_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <title>{% block title %}{% endblock %}</title>
   <link rel="stylesheet" href="//at.alicdn.com/t/font_1332342_viwtvz6jq3.css">
   <link rel="stylesheet" href="{% static '/css/common/auth.min.css' %}">
   {% include 'base/csrf_include.html' %}
   {% block head %}{% endblock %}

   <style>
      .highlighted {
         color: red;
      }
   </style>
</head>
<body>
<header class="header">
   <div class="container">
      <div class="logo-box">
         <a href="{% url 'index' %}"></a>
      </div>

      <ul class="nav">
         <li class="active"><a href="/">创业资讯</a></li>
         <li><a href="{% url 'course:course-index' %}">创业课堂</a></li>
         <li><a href="{% url 'payinfo:index' %}">付费资讯</a></li>
         <li><a href="/search/">搜索</a></li>
      </ul>

      <div class="auth-box">
         <i class="icon-person iconfont"></i>
         {% if user.is_authenticated %}
            <a href="#" class="authenticated-box">{{ user.username }}</a>
            <div class="user-more-box">
               <i class="triangle"></i>
               {% if user.is_staff %}
                  <a href="{% url 'cms:index' %}">管理系统</a>
               {% endif %}
               <a href="{% url 'account:logout' %}">退出登录</a>
            </div>
         {% else %}
            <a href="#" class="signin-btn">登录</a> /
            <a href="#" class="signup-btn">注册</a>
         {% endif %}

      </div>
   </div>
</header>

{% block main %}{% endblock %}


<div class="mask-wrapper">
   <div class="auth-wrapper">
      <div class="close-wrapper">
         <span class="close-btn icon-baseline-close-px iconfont"></span>
      </div>
      <div class="auth-inner-wrapper">
         <div class="scroll-wrapper">
            <div class="signin-group auth-group">
               <div class="top-group">
                  <span class="title">请登录</span>
                  <a href="javascript: void(0);" class="switch">立即注册></a>
               </div>
               <div class="form-group">
                  <div class="input-group">
                     <input type="text" class="form-control" name="telephone" placeholder="请输入手机号码">
                  </div>
                  <div class="input-group">
                     <input type="password" class="form-control" name="password" placeholder="请输入密码">
                  </div>
                  <div class="input-group">
                     <label class="remember-label">
                        <input type="checkbox" name="remember" value="1">
                        记住我
                     </label>
                  </div>
                  <div class="input-group">
                     <input type="submit" class="submit-btn" value="立即登录">
                  </div>
               </div>
            </div>
            <div class="signup-group auth-group">
               <div class="top-group">
                  <span class="title">请注册</span>
                  <a href="javascript: void(0);" class="switch">立即登录></a>
               </div>
               <div class="form-group">
                  <div class="input-group">
                     <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                  </div>
                  <div class="input-group">
                     <div class="short-input-group">
                        <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
                     </div>
                     <div class="input-group-addon">
                        <span class="sms-captcha-btn">发送验证码</span>
                     </div>
                  </div>
                  <div class="input-group">
                     <input type="text" class="form-control" name="username" placeholder="用户名">
                  </div>
                  <div class="input-group">
                     <input type="password" class="form-control" name="password1" placeholder="密码">
                  </div>
                  <div class="input-group">
                     <input type="password" class="form-control" name="password2" placeholder="确认密码">
                  </div>
                  <div class="input-group">
                     <div class="short-input-group">
                        <input type="text" class="form-control" name="img_captcha" placeholder="图形验证码">
                     </div>
                     <div class="input-group-addon">
                        <img src="{% url 'account:img_captcha' %}" alt="" class="img-captcha">
                     </div>
                  </div>
                  <div class="input-group">
                     <input type="submit" class="submit-btn" value="立即注册">
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

<footer class="footer">
   <div class="top-group">
      <div class="top-inner-group">
         <div class="logo-box"></div>
         <div class="detail-group">
            <div class="line1">
               <ul class="links">
                  <li><a href="#">关于小饭桌</a></li>
                  <li><a href="#">创业课堂</a></li>
                  <li><a href="#">寻求报道</a></li>
                  <li><a href="#">创业礼包</a></li>
               </ul>
               <div class="about-us">
                  <span class="title">关于我们：</span>
                  <ul class="social-group">
                     <li class="weixin">
                        <div class="wx-qrcode"></div>
                        <span class="text">xfz008</span>
                     </li>
                     <li class="weibo">
                        <a class="text" href="{% url 'course:course-index' %}">小饭桌创业课堂</a>
                     </li>
                  </ul>
               </div>
            </div>
            <div class="line2">
               <p class="address">地址：北京市朝阳区东三环北路38号院1号楼17层2001内1、16室</p>
               <p class="contact">联系方式：400-810-1090（工作日10点-18点）</p>
            </div>
         </div>
      </div>
   </div>
   <div class="bottom-group">
      ©2017 北京子木投资顾问有限公司 京ICP备15051289号-1
   </div>
</footer>


{#js 文件稍后加载#}
<script src="{% static 'js/message.min.js' %}"></script>
<script src="{% static 'js/front_base.min.js' %}"></script>
</body>
</html>